export interface Company {
  id: string;
  exchange: string;
  name: string;
  sector: string;
  currency: string;
  marketCap: string;
  pe: number;
  eps: number;
  revenue: string;
  netProfit: string;
  high52w: number;
  low52w: number;
  analystBuy: number;
  analystHold: number;
  analystSell: number;
  analystTotal: number;
  consensus: string;
  description: string;
  region: 'india' | 'global';
}

export const COMPANIES: Company[] = [
  {
    id: 'RELIANCE',
    exchange: 'NSE',
    name: 'Reliance Industries',
    sector: 'Conglomerate',
    currency: '₹',
    marketCap: '₹19.4L Cr',
    pe: 23.4,
    eps: 59.90,
    revenue: '₹9,74,864 Cr',
    netProfit: '₹79,020 Cr',
    high52w: 1608.00,
    low52w: 1201.05,
    analystBuy: 18,
    analystHold: 3,
    analystSell: 1,
    analystTotal: 22,
    consensus: 'BUY',
    description: "India's largest conglomerate. Jio telecom, Reliance Retail, and O2C business. Mukesh Ambani led.",
    region: 'india',
  },
  {
    id: 'TCS',
    exchange: 'NSE',
    name: 'Tata Consultancy Services',
    sector: 'IT Services',
    currency: '₹',
    marketCap: '₹14.8L Cr',
    pe: 28.1,
    eps: 150.20,
    revenue: '₹2,40,893 Cr',
    netProfit: '₹46,099 Cr',
    high52w: 4592.25,
    low52w: 3591.50,
    analystBuy: 15,
    analystHold: 7,
    analystSell: 2,
    analystTotal: 24,
    consensus: 'HOLD',
    description: "Largest Indian IT company. 600K+ employees across 55 countries. Tata Group flagship.",
    region: 'india',
  },
  {
    id: 'HDFCBANK',
    exchange: 'NSE',
    name: 'HDFC Bank',
    sector: 'Banking',
    currency: '₹',
    marketCap: '₹12.6L Cr',
    pe: 17.8,
    eps: 94.10,
    revenue: '₹2,87,340 Cr',
    netProfit: '₹64,062 Cr',
    high52w: 1880.00,
    low52w: 1431.80,
    analystBuy: 21,
    analystHold: 4,
    analystSell: 1,
    analystTotal: 26,
    consensus: 'BUY',
    description: "India's largest private sector bank. Post-merger with HDFC Ltd. Strong retail franchise.",
    region: 'india',
  },
  {
    id: 'INFY',
    exchange: 'NSE',
    name: 'Infosys',
    sector: 'IT Services',
    currency: '₹',
    marketCap: '₹6.2L Cr',
    pe: 22.6,
    eps: 66.20,
    revenue: '₹1,53,670 Cr',
    netProfit: '₹26,248 Cr',
    high52w: 1975.00,
    low52w: 1358.35,
    analystBuy: 13,
    analystHold: 7,
    analystSell: 2,
    analystTotal: 22,
    consensus: 'BUY',
    description: "Global IT services leader. Strong in digital transformation, cloud, and AI services.",
    region: 'india',
  },
  {
    id: 'BAJFINANCE',
    exchange: 'NSE',
    name: 'Bajaj Finance',
    sector: 'NBFC',
    currency: '₹',
    marketCap: '₹4.8L Cr',
    pe: 28.9,
    eps: 271.50,
    revenue: '₹55,046 Cr',
    netProfit: '₹14,451 Cr',
    high52w: 8190.00,
    low52w: 6187.50,
    analystBuy: 17,
    analystHold: 3,
    analystSell: 1,
    analystTotal: 21,
    consensus: 'BUY',
    description: "India's leading NBFC. Consumer lending, SME loans, deposits. 85M+ customers.",
    region: 'india',
  },
  {
    id: 'WIPRO',
    exchange: 'NSE',
    name: 'Wipro',
    sector: 'IT Services',
    currency: '₹',
    marketCap: '₹2.6L Cr',
    pe: 19.2,
    eps: 22.80,
    revenue: '₹89,818 Cr',
    netProfit: '₹11,775 Cr',
    high52w: 571.90,
    low52w: 420.00,
    analystBuy: 8,
    analystHold: 10,
    analystSell: 4,
    analystTotal: 22,
    consensus: 'HOLD',
    description: "Global IT services. Focused on cloud, data, and digital transformation.",
    region: 'india',
  },
  {
    id: 'AAPL',
    exchange: 'NASDAQ',
    name: 'Apple Inc.',
    sector: 'Consumer Electronics',
    currency: '$',
    marketCap: '$3.37T',
    pe: 32.8,
    eps: 6.57,
    revenue: '$391.04B',
    netProfit: '$93.74B',
    high52w: 237.49,
    low52w: 164.08,
    analystBuy: 28,
    analystHold: 8,
    analystSell: 2,
    analystTotal: 38,
    consensus: 'BUY',
    description: "iPhone ecosystem, Mac, iPad, Services. $3T+ market cap. Services segment growing 14% YoY.",
    region: 'global',
  },
  {
    id: 'MSFT',
    exchange: 'NASDAQ',
    name: 'Microsoft Corporation',
    sector: 'Software / Cloud',
    currency: '$',
    marketCap: '$3.24T',
    pe: 36.4,
    eps: 12.05,
    revenue: '$245.12B',
    netProfit: '$88.14B',
    high52w: 468.35,
    low52w: 344.79,
    analystBuy: 35,
    analystHold: 5,
    analystSell: 1,
    analystTotal: 41,
    consensus: 'STRONG BUY',
    description: "Azure cloud, Office 365, Copilot AI. Strongest AI monetization among big tech.",
    region: 'global',
  },
  {
    id: 'NVDA',
    exchange: 'NASDAQ',
    name: 'NVIDIA Corporation',
    sector: 'Semiconductors',
    currency: '$',
    marketCap: '$3.11T',
    pe: 48.2,
    eps: 2.53,
    revenue: '$130.50B',
    netProfit: '$72.88B',
    high52w: 153.13,
    low52w: 47.32,
    analystBuy: 38,
    analystHold: 4,
    analystSell: 1,
    analystTotal: 43,
    consensus: 'STRONG BUY',
    description: "GPU monopoly for AI training. H100/H200/B200 data center chips. 78% gross margins.",
    region: 'global',
  },
  {
    id: 'GOOGL',
    exchange: 'NASDAQ',
    name: 'Alphabet Inc.',
    sector: 'Internet / Advertising',
    currency: '$',
    marketCap: '$2.11T',
    pe: 21.3,
    eps: 8.04,
    revenue: '$350.02B',
    netProfit: '$94.32B',
    high52w: 207.05,
    low52w: 140.53,
    analystBuy: 31,
    analystHold: 7,
    analystSell: 1,
    analystTotal: 39,
    consensus: 'BUY',
    description: "Search, YouTube, Google Cloud, Gemini AI. Lowest P/E among Mag7. Strong buybacks.",
    region: 'global',
  },
  {
    id: 'AMZN',
    exchange: 'NASDAQ',
    name: 'Amazon.com Inc.',
    sector: 'E-commerce / Cloud',
    currency: '$',
    marketCap: '$2.31T',
    pe: 44.1,
    eps: 5.02,
    revenue: '$620.13B',
    netProfit: '$59.25B',
    high52w: 242.52,
    low52w: 151.61,
    analystBuy: 37,
    analystHold: 4,
    analystSell: 1,
    analystTotal: 42,
    consensus: 'STRONG BUY',
    description: "AWS cloud leader, e-commerce, Prime Video, advertising. AWS growing 17% YoY.",
    region: 'global',
  },
  {
    id: 'META',
    exchange: 'NASDAQ',
    name: 'Meta Platforms Inc.',
    sector: 'Social Media / AI',
    currency: '$',
    marketCap: '$1.61T',
    pe: 27.6,
    eps: 23.86,
    revenue: '$164.50B',
    netProfit: '$62.36B',
    high52w: 740.91,
    low52w: 414.50,
    analystBuy: 33,
    analystHold: 6,
    analystSell: 1,
    analystTotal: 40,
    consensus: 'BUY',
    description: "Facebook, Instagram, WhatsApp. Llama open source AI. Ray-Ban smart glasses growing.",
    region: 'global',
  },
];

export const YAHOO_SYMBOLS: Record<string, string> = {
  RELIANCE:   'RELIANCE.NS',
  TCS:        'TCS.NS',
  HDFCBANK:   'HDFCBANK.NS',
  INFY:       'INFY.NS',
  BAJFINANCE: 'BAJFINANCE.NS',
  WIPRO:      'WIPRO.NS',
  AAPL:       'AAPL',
  MSFT:       'MSFT',
  NVDA:       'NVDA',
  GOOGL:      'GOOGL',
  AMZN:       'AMZN',
  META:       'META',
};
